name: Meterian Scanner workflow

on: push

jobs:
    meterian_scan_prs:
        name: Meterian scan (PRs routine)
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Meterian Scanner
            uses: MeterianHQ/meterian-github-action@meterian-pr-integration
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
              GITHUB_TOKEN: ${{ github.token }}
              PR_MODE: bysln
            with:
              autofix_security: safe
              autofix_stability: safe
              autofix_with_pr: true
